### ISSUE TITLE
Setting up AWS hosting for images

### ISSUE THREAD

**Issue by shouston3** [LDMW/app#112]
Doing this sooner rather than later will help with #31 and since this is going to eventually happen, we can sort out the [static IPAddress](https://github.com/LDMW/app/issues/10#issuecomment-296226931)

@iteles what would be a good sprint to implement on this?

**Comment by iteles** [comment]
We need to determine the _need_ for image hosting. From what we have seen and discussed _so far_, there hasn't been much. The need will determine the timeline 👍

**Comment by iteles** [comment]
@ellemindwave This is what we were just discussing.

As you can see from #31 , we will need a fair chunk of work if we need to use images for the website through wagtail - this is because the only way wagtail will allow us to interact with images is to upload them and we need to set up where wagtail would upload them _to_.

I don't think this will be a high priority until we _need_ images, but wanted to flag this to you in case you catch a whiff of it being required in future.

**Comment by shouston3** [comment]
Implementing this as of #349
