### ISSUE TITLE
Styling/UX changes

### ISSUE THREAD

**Issue by iteles** [LDMW/app#258]
As a service user, I want the service to look professional and well made, so that I trust it and have confidence in using it. 

Filters:
+ [x] Move Close button to top right of filters and make it a cross
+ [x] Make 'Select as many as are relevant' font size bigger (at least 14px)

Likes/Dislikes
+ [x] 'Thank you for your feedback' when you provide like/dislike feedback should be styled in the same way as the rest of the site
+ [x] Changing wording on inputs to 'Why would you recommend this?' and 'Why wouldn't you recommend this?'

Others:
+ [x] Padding on left of alpha block should be the same as the London Minds text at the top
+ [x] Feedback form back button needs to be made to secondary button styling
+ [x] 'Thank you for your feedback' when you provide 'What are you looking for' feedback should be styled in the same way as the rest of the site

**Comment by indiamindwave24** [comment]
**Filters:**

- [ ] Move Close button to top right of filters and make it a cross
_Can this 'x' be styled as a button, please_

- [ ]  Make 'Select as many as are relevant' font size bigger (at least 14px)
This is still smaller than body text within dropdown. Please make them the same size
<img width="308" alt="screen shot 2017-06-02 at 12 00 24 pm" src="https://cloud.githubusercontent.com/assets/25007700/26723190/3c61d530-478b-11e7-953a-0d052ac0dee4.png">

**Likes/Dislikes**

- [ ]  'Thank you for your feedback' when you provide like/dislike feedback should be styled in the same way as the rest of the site

- [ ]  Changing wording on inputs to 'Why would you recommend this?' and 'Why wouldn't you recommend this?'

**Others:** 

- [ ] Padding on left of alpha block should be the same as the London Minds text at the top
_ think the issue here is the 'What are you looking for?' module... Please check that padding is consistent throughout site_

- [ ]  Feedback form back button needs to be made to secondary button styling

- [ ]  'Thank you for your feedback' when you provide 'What are you looking for' feedback should be styled in the same way as the rest of the site

_____

- [ ] I have noticed another edit that is required - there is no hover state on 'get urgent support' link
_I have included in the style guide https://github.com/LDMW/app/issues/282_

**Comment by sarahwelton** [comment]
Just want to make sure we've got this issue flagged too: 
![screen shot 2017-06-06 at 16 05 07](https://cloud.githubusercontent.com/assets/26305143/26836149/fccd6192-4ad1-11e7-92fc-c74bc2e47404.png)

**Comment by sarahwelton** [comment]
Just for clarification @Danwhy , I think - and @indiamindwave24 can confirm - that the input box and text needs to line up with the the content panels.
