### ISSUE TITLE
Email and input validation

### ISSUE THREAD

**Issue by iteles** [LDMW/app#259]
As an admin, I want users to be told if they are inputting an email in an incorrect format so that I don't get incorrect feedback.

As a service user, I want to be alerted to the fact that the email I have entered is not a valid format so that I don't accidentally enter the wrong details

## Acceptance Criteria
+ [x] Users get an alert when an email is input in an incorrect format, letting them know they need to correct this
+ [x] Users cannot submit an email in an incorrect format
+ [x] This happens in the homepage alpha block and in the feedback form

**Comment by sarahwelton** [comment]
I'm just reading a bit about dotless email addresses (I was confused that I could enter sarah@mindwave as a valid email when I was testing!) and it what I've read so far suggests that it's more likely that a dotless email being entered would be an error rather than deliberate... Do you guys have a sense of how common they are? If not at all common, perhaps we should notify users of an error if they do enter a dotless email address... What do you think @iteles ?

**Comment by iteles** [comment]
@sarahwelton They're not very prevalent for now, I reckon you're right here, let's include the dot in the validation until user feedback tells us otherwise.

**Comment by shouston3** [comment]
I've made the dot required in emails
