### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by indiamindwave24** [LDMW/app#281]
As a user, I want to see a London Minds favicon in my browser tab when I have the London Minds site open, so that I can easily recognise it amongst my other tabs

Acceptance Criteria
- [x] Favicon appears next to page title
- [x] Favicon is styled according to @indiamindwave24 's design below

![favicon-01-01](https://cloud.githubusercontent.com/assets/25007700/26720141/fcbb44fe-477e-11e7-984e-58274e9df723.png)
Do let me know if there are any issues with this

**Comment by shouston3** [comment]
@Danwhy we should convert this to an `.ico` format. Perhaps using [this](http://icoconvert.com/)?

**Comment by indiamindwave24** [comment]
@shouston3 it appears pixelated/fuzzy
<img width="99" alt="screen shot 2017-06-06 at 16 12 23" src="https://user-images.githubusercontent.com/25007700/26836660-60fd7aac-4ad3-11e7-82da-82e34bc9d8e4.png">

**Comment by sarahwelton** [comment]
I put it through an icon converter that doesn't change dimensions to make it square - perhaps thats why its looking pixelated (and proportions look a bit off??) because its tried to keep it in a square space with the little tail bit... 

Not sure whether you need ALL of these (or whether you can just use one across all devices!? But as I was having a play anyway, perhaps they'll be of some use........... 

![android-icon-36x36](https://user-images.githubusercontent.com/26305143/26836928-17dca54a-4ad4-11e7-9b35-4534c5a542fa.png)
![android-icon-48x48](https://user-images.githubusercontent.com/26305143/26836929-17dd9464-4ad4-11e7-950c-266f007c4d32.png)
![android-icon-72x72](https://user-images.githubusercontent.com/26305143/26836931-17e31cea-4ad4-11e7-8b57-e48b79b09078.png)
![android-icon-96x96](https://user-images.githubusercontent.com/26305143/26836930-17e27984-4ad4-11e7-90ad-c3e65e8a7c37.png)
![android-icon-144x144](https://user-images.githubusercontent.com/26305143/26836932-17e3c65e-4ad4-11e7-8c0b-f533231664ee.png)
![android-icon-192x192](https://user-images.githubusercontent.com/26305143/26836933-17e90c86-4ad4-11e7-9753-417c68393a11.png)
![apple-icon-57x57](https://user-images.githubusercontent.com/26305143/26836936-17fcc9ce-4ad4-11e7-938c-3d4f43a772c9.png)
![apple-icon-60x60](https://user-images.githubusercontent.com/26305143/26836934-17f437aa-4ad4-11e7-8680-675f419f2289.png)
![apple-icon-72x72](https://user-images.githubusercontent.com/26305143/26836947-184719f2-4ad4-11e7-80c4-49cf8b42bd7d.png)
![apple-icon-76x76](https://user-images.githubusercontent.com/26305143/26836935-17f82662-4ad4-11e7-849d-6ed5872c6bf0.png)
![apple-icon-114x114](https://user-images.githubusercontent.com/26305143/26836937-17fdb334-4ad4-11e7-9d31-08a8eb9886a9.png)
![apple-icon-120x120](https://user-images.githubusercontent.com/26305143/26836938-17fdeda4-4ad4-11e7-81a8-7ae12139a9de.png)
![apple-icon-144x144](https://user-images.githubusercontent.com/26305143/26836940-18189906-4ad4-11e7-9bda-44f2fb4a4bf5.png)
![apple-icon-152x152](https://user-images.githubusercontent.com/26305143/26836939-1818dd58-4ad4-11e7-902d-2e0577423859.png)
![apple-icon-180x180](https://user-images.githubusercontent.com/26305143/26836954-1b182126-4ad4-11e7-9dde-65d015294501.png)
![apple-icon-precomposed](https://user-images.githubusercontent.com/26305143/26836942-181e01f2-4ad4-11e7-93af-e33995835d0f.png)
![apple-icon](https://user-images.githubusercontent.com/26305143/26836941-18197c72-4ad4-11e7-9d8f-d46e81cf7d8f.png)

![favicon-16x16](https://user-images.githubusercontent.com/26305143/26836944-18317ab6-4ad4-11e7-9f58-f752445fed0b.png)
![favicon-32x32](https://user-images.githubusercontent.com/26305143/26836943-182e88b0-4ad4-11e7-9bbf-253678d69fa6.png)
![favicon-96x96](https://user-images.githubusercontent.com/26305143/26836945-18353610-4ad4-11e7-89a5-b6b8f710b4ac.png)


![ms-icon-70x70](https://user-images.githubusercontent.com/26305143/26836948-18522612-4ad4-11e7-8dee-af5c5d1e8518.png)
![ms-icon-144x144](https://user-images.githubusercontent.com/26305143/26836950-18590482-4ad4-11e7-9f73-f14433cc381c.png)
![ms-icon-150x150](https://user-images.githubusercontent.com/26305143/26836949-1855a9cc-4ad4-11e7-85a7-d28a820d307b.png)
![ms-icon-310x310](https://user-images.githubusercontent.com/26305143/26836951-1860fa7a-4ad4-11e7-8d13-8446b2dae83b.png)

**Comment by sarahwelton** [comment]
Would be useful if they had kept their file names next to them haha! They are named as per the device they are suitable for...

**Comment by sarahwelton** [comment]
Also have just realised that you don't really see favicons on phones anymore...

**Comment by sarahwelton** [comment]
Sorry to keep bombarding this thread - also:

- is it the favicon that should pull through to your phone homescreen when you save a website to your homescreen? (Mine is saving as a white "H" in a blue square) 

- is it the favicon that pulls through to your "most visited" on your browser?
