### ISSUE TITLE
Load testing

### ISSUE THREAD

**Issue by iteles** [LDMW/app#315]
As part of our preparation for mental health week, we need to ensure we're load testing this week.

See @nelsonic's comment [here](https://github.com/healthlocker/healthlocker/issues/804#issuecomment-307066988) for a place to start.

**Comment by shouston3** [comment]
How much user load should we be expecting and testing for with [artillery](https://artillery.io/)?

**Comment by iteles** [comment]
Worth also asking @sarahwelton and @ellemindwave for load expectations.

**Comment by nelsonic** [comment]
Load Testing a _Brand New_ Website is kinda futile unless you _know_ up-front that there's a _massive_ PR/Marketing campaign e.g: front-page of BBC News, Redit or similar. 

From _experience_ unless you _know_ how many users are _already_ signed up to an app/product and have stats for open rates it's _pointless_ to estimate more than 10k users.

And since a Phoenix App (_that is mostly static content_) can _easily_ handle 10k users _concurrently_ on _modest_ hardware (_i.e. 1 Heroku Dyno_) a _much_ more fruitful discussion is to ask what are the **_current_ bottlenecks** in the application?

Artillery is not going to give us a page load profile. 
Whereas PageSpeed _is_ going to be _very_ insightful:
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fldmw-app-staging.herokuapp.com

![image](https://user-images.githubusercontent.com/194400/26933784-72a71b4a-4c5f-11e7-971f-eff5c9e1d26f.png)

Most people "_Over-Provision_" on infrastructure out of "FUD" when they _really_ just need _real-time_ analytics to know _exactly_ what the demand is.

**Comment by iteles** [comment]
@nelsonic To clarify, from Wednesday of next week onwards, there will be a (unexpected, we found out today) PR blitz across multiple media outlets publicising London Minds for Mental Health Week so I suggest we need some level of preparedness as we won't have any 'real' visitors before then given the decision to remove it from Google #222 (which of course, is 180 degrees from the PR blitz).

**Comment by iteles** [comment]
Closing in favour of https://github.com/LDMW/app/issues/359 as per the comment above.
