### ISSUE TITLE
a11y issue | Multiple labels associated with one form control

### ISSUE THREAD

**Issue by iteles** [LDMW/app#316]
Spotted this a11y issue when running the website through [WAVE](http://wave.webaim.org/report#/https://ldmw-app-staging.herokuapp.com/) on staging:
<img width="386" alt="screen shot 2017-06-08 at 13 05 00" src="https://user-images.githubusercontent.com/4185328/26927920-cb0ed8ea-4c4b-11e7-8b1e-3f739a54386b.png">

**Comment by Danwhy** [comment]
According to WAVE we can fix this by adding an 'aria-labelledby' attribute to the checkbo that has multiple labels:
<img width="222" alt="screen shot 2017-06-09 at 10 17 27" src="https://user-images.githubusercontent.com/8939909/26969262-0a399bb6-4cfd-11e7-91ab-d2c8f61572c4.png">

The problem with having two labels is that screen readers won't know which label to read. Having aria-labelledby attributes allows screen readers to know that both labels apply, so this should fix the issue

I've done this in e1986d0, but WAVE is still saying it's an error because it has two labels. I don't know if this is actually still a problem, or if the fix is correct and WAVE just isn't able to detect it.

**Comment by iteles** [comment]
This fix works on screen readers, let's open it again if accessibility issues are reported.
