### ISSUE TITLE
Restyling tags on resources to make them less bulky

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#328]
As a user, I want to see more of the content itself in the search results and not have too much space taken up by the content tags, so that I can fit more on my screen and see more content

Acceptance Criteria
- [ ] Restyling of visible content tags according to wireframes / UI from Sarah & India

**Comment by ellemindwave** [comment]
![screen shot 2017-06-12 at 10 26 13](https://user-images.githubusercontent.com/26304634/27027513-a33e6518-4f59-11e7-8bfe-a682d11b9494.png)

**Comment by iteles** [comment]
@ellemindwave This wasn't actually part of our agreed sprint scope for sprint 5.

If we do have time to fit this in though, I just wanted to confirm this is still a requirement.
With #329 I feel that we want these tags to feel like tags and invite people to click them. From my experience of user testing in the past, this means we need to make them look like tags or buttons rather than plain text as we have above.

I understand these are still wireframes but as we won't have designs to go on for this sprint (according to our conversation earlier today), it would be good to have confirmation from you that the above has been discussed 😊

**Comment by ellemindwave** [comment]
@iteles thanks for this. @indiamindwave24 is working on the UI overhaul, and yes, the tags look like tags! So this issue can be closed now. 

@sarahwelton just checking you agree?

**Comment by sarahwelton** [comment]
yup
