### ISSUE TITLE
Make tags clickable (showing all content relevant to that tag)

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#329]
As a user, I want to be able to click on a particular tag and be directed to all of the content that is relevant to that tag, so that I can explore and potentially find more resources that could help me

AC
- [x] Tags are clickable
- [x] Click on a tag directs to all content under that tag

**Comment by sarahwelton** [comment]
@shouston3 the font has changed on the tags - just want to ensure this won't be the case on live.

**Comment by shouston3** [comment]
@sarahwelton nice spot, looking into this

**Comment by shouston3** [comment]
@sarahwelton This font issue should now be addressed

**Comment by iteles** [comment]
@shouston3 We also need to fix the number of results text:
It still say 'showing 22 results for... forum (for example)' when there are only a handful

<img width="401" alt="screen shot 2017-06-21 at 15 26 35" src="https://user-images.githubusercontent.com/4185328/27389360-0ef00d14-5696-11e7-94b3-d937bff9d4ef.png">

**Comment by iteles** [comment]
@sarahwelton @indiamindwave24 We've come across a very interesting problem with this clickable tags issue which we hadn't accounted for when we were sprint planning: the interaction between the clickable tags and the filter sidebar.

As it has currently been built:
+ User clicks on `forum` tag within a resource
+ Content is filtered by `forum` tag in the filter sidebar (which is useful as a user then is able to see what filtering has been applied):
<img width="377" alt="screen shot 2017-06-22 at 21 45 19" src="https://user-images.githubusercontent.com/4185328/27455126-28fa8528-5794-11e7-9ad9-94683fefb832.png">
+ HOWEVER, because of the request that the sidebar filters be set up as 'OR's (I'd be very interested to know if user testing has confirmed this is the users' expectation), the search still shown 22 results because it's basically expecting forum to be an option, not the _only_ option

_If the expectation is that when a user clicks on a tag in a resource they only see other resources that have that tag (which I imagine is the desired behaviour_, this means we're now in a situation where clicking on the tag in the resource has a different effect to selecting that same tag from the sidebar.

So the question we have is: **should there be any interaction between the sidebar and the clickable tags and if so, what should it be?**

**Comment by sarahwelton** [comment]
The only issue that we've come across in user testing is that a user would like to see the tags that they've selected in the filters highlighted on the piece of content.  But we didn't have enough time within the sprint to get that in as it wasnt a major issue.

**Comment by sarahwelton** [comment]
We'll make sure we test this. Users want to click on tags. I think it's clear that this amends the filter selection but we will keep an eye on it.

**Comment by sarahwelton** [comment]
Sorry... I think I'm confused!! Clicking on "forum" should filter the content to only show resources that are tagged with "forum". Is this what is happening??

**Comment by iteles** [comment]
@sarahwelton The expected behaviour is clear, thanks! This has led us to understand a couple of things about how filtering is happening at the moment, which we'll look to fix in this sprint too #410
