### ISSUE TITLE
Set up reusable components

### ISSUE THREAD

**Issue by Danwhy** [LDMW/app#34]
Set up the helper functions required to render reusable components with fixed styling

**Comment by iteles** [comment]
@Danwhy This is what @Cleop will be working on with you tomorrow as well 👍

**Comment by Cleop** [comment]
The basis for the type of standard components that we will be building comes from those used on Research Resource (as opposed to Healthlocker). The RR style of components are seen as preferable to the HL ones for 2 main reasons:

![image](https://cloud.githubusercontent.com/assets/16775804/25524549/ef26dde0-2c02-11e7-9600-5358ba17aac8.png)


1. **You can add custom classes to them.**
E.g. A primary button is styled in a certain way but needs a positioning class as well for its use in certain instances, this can be added by custom and gives the freedom to specify when/what it's needed for. In the HL components you had to place these components in a div in order to overcome this shortfall and it was something that the team had discussed wanting to overcome.
2. **The components are easier to find for designers/ front end devs who do not know elixir/phoenix.**
This is because in the RR examples all of the files were stored in a components folder and every time a component was used it involves the word 'component' in the tags to call it. This means that a user of the guide can see clearly in that one folder whether a component exists/ what it looks like. Equally, a user can read the code searching for/locating components by looking for the word 'component' as a cue. I think this is useful because otherwise (particularly in the case of partials standard components), it can be difficult for non-phoenix devs to tell the difference between a whole page partial, any phoenix function and a component partial.

@nelsonic, do let me know if you'd like to see any specific code examples to help flesh this out.

**Comment by shouston3** [comment]
The RR component style was inspired by this article: http://blog.danielberkompas.com/2017/01/17/reusable-templates-in-phoenix.html

**Comment by Cleop** [comment]
Still to do:

- [ ] Links

**Comment by shouston3** [comment]
Adding these components in #239, will close when merged
