### ISSUE TITLE
Styling of 'add your own' in filters

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#366]
As a user, I want to know that the 'add your own' feature in the filters is a different feature to simply selecting an option, so that I am not confused as to its function

- [ ] Styling according to @indiamindwave24

**Comment by indiamindwave24** [comment]
Use previous styling of filters at this stage but add a text box (following previous styling) and a search button after the filters.
<img width="883" alt="screen shot 2017-06-21 at 13 48 40" src="https://user-images.githubusercontent.com/25007700/27384852-60549a84-5688-11e7-9899-b16c08b4d0d5.png">

**Comment by iteles** [comment]
@indiamindwave24 Do we need to incorporate the cross at the moment? If so, what is the collapsed state of this?
At the moment it isn't in the wireframes #19 so we hadn't considered it yet.

**Comment by indiamindwave24** [comment]
This is the same as what was built in sprint 1/2.

when the 'x' is clicked, the module collapses to the filter button. When filter is clickded, this module reopens

**Comment by indiamindwave24** [comment]
......Decision at MV which will probably make all of your lives a bit easier. 

No closing. Remove the x button. Filter buttons sit open as standard 👍

**Comment by iteles** [comment]
@indiamindwave24 I've just realised that the above screenshots aren't actually relevant to this issue (I clicked into the notification which took me straight to the comment rather than the title of the issue :blush:).

This issue is dealing with the 'Add your own' filters in the sidebar and them having to be differentiated from the rest of the tags in the drop-down.

These designs are for https://github.com/LDMW/app/issues/334

**Comment by sarahwelton** [comment]
I think there's some confusion here. We don't have time to amend the styling of this feature so let's close and revisit.
