### ISSUE TITLE
Site went down

### ISSUE THREAD

**Issue by shouston3** [LDMW/app#434]
Earlier today when deploying to production the live site went down for a few hours.

We are fairly sure that this is a result of our queries operating over a much larger data set than before (the now much larger set of resources with many tags), the tables generated from doing multiple `full_join`s becoming very large and the database request either crashing or timing out (it was taking longer than 30 seconds to run before timing out).

@Danwhy has since swapped over the the database we read from to be the `staging` database just so that there is some content on the site.

We initially tried to revert our wagtail migration, but running the `django` migration commands generated a number of migrations for different sections of the database. It was too difficult to work out the exact ones to revert back to for the different sections.

We should fix this issue by making smaller joins [here](https://github.com/LDMW/app/blob/master/web/controllers/resources.ex#L62) and [here](https://github.com/LDMW/app/blob/master/web/controllers/resources.ex#L101)

**Comment by Danwhy** [comment]
The real issue is with [this line](https://github.com/LDMW/app/blob/master/web/controllers/resources.ex#L176) and the one below it. These functions are being called on each resource, and making a query to get all the tags/likes for that resource. On the live site, that means over 200 queries are being made just to get the homepage.

The answer is to either perform a more complicated query in the first place when we get the resources to get the tags as well, or to get fewer resources initially.

**Comment by reddog** [comment]
Thanks @Danwhy  & @shouston3 for bringing this to everyone's attention.

The live site is currently listing "22 resources about wellbeing" as is the staging site.  Does this mean that the live site is still looking at the staging database?

**I would suggest that this is probably quite a high priority issue, particularly in light of the next Brighton demo which happens tomorrow with further key stakeholders.**

In the immediate term, I think we need to get the live site back up and running.  This is either:

1. revert the changes and get back to showing the site pre-Wednesday and with live data
2. fix the release so that the new functionality works with live data.

The choice will depend on timescale.  I notice that no one is currently assigned to this issue.  When are you expecting that it will be resolved?

If fixing the release is a big job, then reverting to a pre-Wednesday version should be the route forward.

What we currently have is new functionality but test data.  It's a bit like having a new feature in your internet banking account (maybe transfer between your own accounts), but you can only see test account balances.  It's great to have a new feature, but not if it can't be used.

Moving forward - **after** the immediate work to fix the current situation has been completed - could you please respond with:

- When was the issue with deployment discovered?  A number of people were in the office for the much of Wednesday and I'm sure we all have a desire to help fix things that break.  How can we all better support fixing such issues in the future?
- What is the general and specific (for this release) deployment plan?  Why was roll back difficult?
- With regard to the testing process on your side - what can we do differently next time to avoid this?  Should the staging database be a copy of the live database (in order to test for similar sized datasets, etc)?

Do let me know if I can help at all.

**Comment by iteles** [comment]
@reddog and team, we're looking into this now.

**Comment by reddog** [comment]
@iteles Thanks for the update

**Comment by reddog** [comment]
@Cleop Which resolution path are you guys currently looking at?  Fixing up the release to use the live database or rolling back?  (or something else)?

Thanks.

**Comment by Cleop** [comment]
The site is now live again and loading the production database.

This was achieved by reversing changes to the query whilst retaining all other changes in this sprint regarding new features.

Still an issue is the missing body content for the production resources. For the time being, the body content for the staging resources has been added to those resources that exist in production. We are working on retrieving the remaining missing content.

**Comment by reddog** [comment]
Thanks for the update @Cleop.

Can you expand on "missing body content".  Is this information that's in the production database but work has to be done to retrieve it in an different way (because previous code was broken/inappropriate maybe)?  Or has data been (at least for the moment) lost from the production database?

**Comment by Cleop** [comment]
The site is now running with the production database data. This data is complete as covered by #437.

Now focussing on revising processes to safeguard for the future.

**Comment by reddog** [comment]
Thanks @Danwhy, @shouston3 & @Cleop for getting the live site back up and running.

@Cleop with regard to revising processes, can you please see my "moving forward" comments above?  Would it be useful to do this in the open as a group?  Maybe when you're next in (which is when)?

**Comment by Cleop** [comment]
@reddog 

- **When was the issue discovered? How can we all better support fixing such issues in the future?**
The issue was discovered on Wednesday evening. A deployment brought the site down (no indication that there were any changes to CMS data at this stage) and so the team set about debugging this. 
At this stage there was a communication issue within our team as @iteles made the assumption that this had been raised by the MV team before the issue was opened, this would normally have been communicated directly by her to the MV team.
They successfully got the site live again within an hour or so by temporarily switching the site to the staging database. This was used instead of the production db because the size of the production db was causing it to crash. They worked as a pair without consulting other team members because of the technical nature of the issue and their relevant skill sets. They picked up the issue the next morning to changeover and resolve the issue with the production db, the missing data issue was not apparent at this time.
Our standard process would see the scrum master discuss possible solutions with the MV team before one is implemented (rolling back or otherwise) and we will ensure communication assumptions aren’t made in future. 
 
- **What is the general and specific (for this release) deployment plan?**
  - [Our general deployment plan](https://github.com/LDMW/app/blob/master/alpha_deployment_plan.md)
  - On this occasion both application states had to be changed at the same time as we were changing some naming in our cms database and this had to be in sync with the app state. Our plan for errors was to fix the issues directly but as a last resort to rollback both databases to their pre-deploy states.
- **Why was rollback difficult?**
The rollback was difficult because of the scale of the migration and the number of apps on wagtail. There are currently 18 applications on wagtail, which contain up to 33 migrations when run. In the circumstance of a rollback you must coordinate and select the correct migration in each app which proved complex.
These are processes that we will refine once the site is out of prototype stage and publicly available, effectively ‘in production’, we will be doing so at the beginning of beta.
- **What can we do differently to avoid this?**
As we move into beta, our deployment processes evolve to the next level, which will include:
  - More frequent deployments (which we have discussed with the MV team at the last few sprint retrospectives) - these were not possible in the last sprint because we weren’t able to work on the styling until the second half of the sprint so could not deploy them.
  - Moving into beta our process is to test staging with a mirror of production data
  - As we dig into data security and hosting concerns as part of beta, we will load test the app regularly as well as implementing further optimisations such as caching.

@shouston3, @Danwhy and I will next be in the week after next (at the beginning of beta) when we can discuss any of these elements in person.

**Comment by shouston3** [comment]
This has now been resolved and we've worked on preventative steps for the future.
