### ISSUE TITLE
Landing/hero image section

### ISSUE THREAD

**Issue by katbow** [LDMW/app#446]
For #433 

- [x] Update to new logo & centre (verify it's updated on all places it's used)
- [x] Change text copy, centre, & increase size (hero title styling)
- [x] Update search bar
    - [x] Make transparent (provided the text can be black. If the text goes grey, make search bar white) #455 
    - [x] On focus, border is orange
    - [x] Centre
    - [x] Move search button to below search bar
    - [x] Change colour & border radius of search button (primary button styling #448)

![image](https://user-images.githubusercontent.com/1287388/27790030-aa6f68ee-5fe6-11e7-9c7b-e7b72f94bf65.png)

**Comment by Cleop** [comment]
Does not reduce the gap between the title text and the search bar quite as much as in the designs:
**Designs:**
![image](https://user-images.githubusercontent.com/16775804/27873116-db73b0ae-61a2-11e7-80c6-ccf20b3eea9d.png)
**Actual:**
![image](https://user-images.githubusercontent.com/16775804/27873122-e1a5b918-61a2-11e7-88ab-cf6c32210a70.png)
This is because the margin is automatically applied to the `<h2>` tag by the CMS and it's not possible to add custom classes directly to the CMS elements. @katbow - do you think it's close enough to the designs or can you think of a solution to this issue?
