### ISSUE TITLE
Results section

### ISSUE THREAD

**Issue by katbow** [LDMW/app#454]
For #433 

- [x] Update tags to new not clickable styling
    - [x] Decrease height
    - [x] Shrink text
    - [x] Change background colour to light orange
- [x] Change "Showing results for" to H2
- [x] Left align filter button & update to secondary white styling
  - [x] Reduce border radius to make less round
  - [x] Change background to white
  - [x] Give blue border
  - [x]  Make text less bold 
  - [x] Make blue background/white text on hover

For each resource styling see #453

![image](https://user-images.githubusercontent.com/1287388/27790095-00937c10-5fe7-11e7-8f9e-c1ed77c4b481.png)

**Comment by katbow** [comment]
@Cleop I'm having some trouble with left aligning the filter button. do you know how the hidden menu & filter interact together?

**Comment by Cleop** [comment]
I managed to do it in inspect doing on the div and section it's in rather than the label itself: 
<img src="https://user-images.githubusercontent.com/16775804/27835823-8fa2ac3a-60d4-11e7-8361-9c722603407a.png" width=350px />
Looks like:
<img src="https://user-images.githubusercontent.com/16775804/27835835-989319ba-60d4-11e7-9c17-bfe4155d8511.png" width=200px />

You could add a tiny bit of left padding onto the <div> if they're not quite inline as the other elements may have horizontal padding too.

Give it a go and let me know if this doesn't work for you

**Comment by katbow** [comment]
Ahh yes that managed to do it. I was trying a couple of different things and it was pushing out the filter menu for some reason. Thanks!

**Comment by katbow** [comment]
Also I checked the guideline & the smaller font was still within the GDS guidelines 👍
